####################Deployment############################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-password-service
  labels:
    app: common-password-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-password-service
  template:
    metadata:
      labels:
        app: common-password-service
    spec:
      containers:
        - name: common-password-service
          image: kesingh/k8is:common-password-service
          ports:
            - containerPort: 9000

---
####################Service#######################
apiVersion: v1
kind: Service
metadata:
  name: common-password-service
spec:
  selector:
    app: common-password-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
