####################Deployment############################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-strength-service
  labels:
    app: password-strength-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-strength-service
  template:
    metadata:
      labels:
        app: password-strength-service
    spec:
      containers:
        - name: password-strength-service
          image: kesingh/k8is:password-strength-service
          ports:
            - containerPort: 8000
---
####################Service#######################
apiVersion: v1
kind: Service
metadata:
  name: password-strength-service
spec:
  selector:
    app: password-strength-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
