####################Deployment############################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-form
  labels:
    app: password-form
spec:
  replicas: 1
  selector:
    matchLabels:
      app: password-form
  template:
    metadata:
      labels:
        app: password-form
    spec:
      containers:
        - name: password-form
          image: kesingh/k8is:password-form
          ports:
            - containerPort: 80
          imagePullPolicy: Always
---
####################Service#######################
apiVersion: v1
kind: Service
metadata:
  name: password-form
spec:
  selector:
    app: password-form
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
