####################Deployment############################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: repeated-password-service
  labels:
    app: repeated-password-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repeated-password-service
  template:
    metadata:
      labels:
        app: repeated-password-service
    spec:
      containers:
        - name: repeated-password-service
          image: kesingh/k8is:repeated-password-service
          ports:
            - containerPort: 7000
---
####################Service#######################
apiVersion: v1
kind: Service
metadata:
  name: repeated-password-service
spec:
  selector:
    app: repeated-password-service
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
